name: 'setup'
description: 'Set up project with dependencies (database, composer...)'
runs:
  using: "composite"
  steps:
    # Setup
    - name: Code checkout
      uses: actions/checkout@v5
    - name: Misc caches
      uses: actions/cache@v4
      with:
        path: |
          .phpstan.cache
        key: ${{ runner.os }}-test-misc-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-test-misc-
    - name: Cache vendor directory
      uses: actions/cache@v4
      with:
        path: ./vendor
        key: ${{ runner.os }}-test-vendor-${{ hashFiles('./composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-test-vendor-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker build
      uses: actions/cache@v4
      with:
        path: /tmp/docker-cache
        key: ${{ runner.os }}-test-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-test-docker-
    - name: Start environment
      shell: bash
      run: docker compose -f compose-ci.yaml --verbose up -d --wait
