#!/bin/bash

### PRE-COMMIT GIT HOOK TO APPLY SYMFONY CODE STYLE
##
## install php-cs-fixer in your system (globally)
## and link this script in your githooks if you want to use it with command below
##
#$ ln -s ../../scripts/githooks/pre-commit .git/hooks/pre-commit

FILES=$(git diff --name-only --diff-filter=AM)
printf '%s\n' "$FILES" | while IFS= read -r FILE
do
    if [[ $FILE == "src/"* ]]; then
        docker exec box-idiomes-php sh -c "vendor/bin/php-cs-fixer fix ${FILE} --config=.php-cs-fixer.dist.php --verbose"
    fi
done
FILES=$(git diff --name-only --staged --diff-filter=AM)
printf '%s\n' "$FILES" | while IFS= read -r FILE
do
    if [[ $FILE == "src/"* ]]; then
        docker exec box-idiomes-php sh -c "vendor/bin/php-cs-fixer fix ${FILE} --config=.php-cs-fixer.dist.php --verbose"
        git add "$FILE"
    fi
done
